# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f8d35b1abd2e04c9299990a8d8074ab15b695ddee1d0d91d7dc9923186ec6eb6654e7cda3cb5c26c4971c8629d1f63fb58f766ca581696efd67dbda75fba0c0

test:
  secret_key_base: 3f90cb88335a42823a47531953ab3ee434789824912f2ba11616ec8d9292be88bd8d9d351ba69f40b190c02b401f36193c1b82415c989a16ca0bf387d8fe8f88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 311bef8db7ec329d7fa73b5c01cbcb1cb0ef17f63a17b9d19c5f67c08df35bcf110c491c1a7f8a247a4509cf02a37ad3f7312d11ba654b4c2bbed67fb7b7484f
